/**
 * AUTO-GENERATED by scripts/build.ts — do not edit.
 */
import onnxDylib from "../../node_modules/onnxruntime-node/bin/napi-v6/darwin/arm64/libonnxruntime.1.24.3.dylib" with {
  type: "file",
};
import onnxNode from "../../node_modules/onnxruntime-node/bin/napi-v6/darwin/arm64/onnxruntime_binding.node" with {
  type: "file",
};
import { setEmbeddedOnnxNatives } from "../embed/onnx-natives.ts";

setEmbeddedOnnxNatives({ node: onnxNode, dylib: onnxDylib });
